apiVersion: v1
kind: Service
metadata:
  name: mandarine-server-lb
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: server
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: mandarine-server
    tier: backend