apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandarine-server
spec:
  selector:
    matchLabels:
      app: mandarine-server
  template:
    metadata:
      labels:
        app: mandarine-server
    spec:
      containers:
      - name: mandarine-server
        image: tsodev/mandarine:1.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
